{
 "title": "DevLight Monitor",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "serviceName",
    "label": "Service Name",
    "query": "SELECT DISTINCT ServiceName FROM otel_traces"
   },
   {
    "name": "trace_id",
    "label": "Trace Id",
    "query": "SELECT DISTINCT TraceId FROM otel_traces WHERE ParentSpanId = '' LIMIT 100"
   }
  ]
 },
 "panels": [
  { "title": "First Page", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Service Map",
   "type": "nodeGraph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT\nServiceName as id,\nServiceName as title,\nAVG(Duration) / 1000 as mainstat, -- 예: 평균 지속 시간(ms)\nCONCAT('req cnt ', CAST(count() AS VARCHAR)) as secondarystat,\n--  AVG(Duration) / 1000 as detail__RESPONSE_TIME, -- 예: 평균 지속 시간(ms)\n--  CAST(count() AS VARCHAR) as detail__REQUEST_COUNT,\nCONCAT(CAST(sum((if(StatusCode = 'STATUS_CODE_ERROR', 1, 0)) * 100) / COUNT() AS VARCHAR) , '%') AS detail__ERROR_RATE,\n\n\nsum(if(StatusCode == 'STATUS_CODE_UNSET', 1, 0)) / COUNT() AS arc__unset_rate,\nsum(if(StatusCode == 'STATUS_CODE_OK', 1, 0)) / COUNT() AS arc__ok_rate,\nsum(if(StatusCode == 'STATUS_CODE_ERROR', 1, 0)) / COUNT() AS arc__error_rate\n-- StatusMessage as secondarystat\nFROM otel_traces\nWHERE ResourceAttributes['user_id'] = 'wnsrb'\nGROUP BY ServiceName",
     "selectedFormat": 4
    },
    {
     "rawSql": "SELECT\nconcat(s.ServiceName, '_', t.ServiceName) as id,\n s.ServiceName as source,\n t.ServiceName as target,\n AVG(t.Duration) / 1000 as detail__RESPONSE_TIME,-- 예: 평균 응답 시간 (ms)\n CAST(count() AS VARCHAR) as detail__REQUEST_COUNT, -- 예: 전체 요청 수\n CONCAT(CAST(sum((if(t.StatusCode = 'ERROR', 1, 0)) * 100) * COUNT() AS VARCHAR) , '%') AS detail__ERROR_RATE\nFROM otel_traces s\nJOIN otel_traces t ON s.SpanId = t.ParentSpanId AND s.TraceId = t.TraceId\nGROUP BY s.ServiceName, t.ServiceName",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Service OverView",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "WITH TotalCount AS (\n    SELECT COUNT(*) as AllRows\n    FROM otel_traces\n)\n\n\nSELECT\n    ServiceName,\n    CONCAT(CAST(ROUND(AVG(Duration) / 1000,2) AS VARCHAR), 'ms') as Response_Times, -- 예: 평균 지속 시간(ms)\n    CONCAT(CAST(ROUND((COUNT(*) * 100.0 / (SELECT AllRows FROM TotalCount)), 2) AS VARCHAR), '%') AS Request_Rates,\n    CONCAT(CAST(ROUND((sum(if(StatusCode = 'STATUS_CODE_ERROR', 1, 0)) * 100.0 / COUNT(*)), 2) AS VARCHAR), '%') AS Error_Rates\nFROM otel_traces\nWHERE  ResourceAttributes['user_id'] = 'wnsrb' AND $__conditionalAll(TraceId IN (${trace_id:singlequote}),  $trace_id) AND $__timeFilter(Timestamp)  AND ServiceName In (${serviceName:singlequote})\nGROUP BY ServiceName\n",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Request Rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "-- WITH TotalCount AS (\n--     SELECT COUNT(*) as AllRows\n--     FROM otel_traces\n    \n-- )\n\n-- SELECT  toStartOfMinute(`Timestamp`) as time, ServiceName, ROUND((COUNT(*) * 100.0 / (SELECT AllRows FROM TotalCount)), 5) \n-- FROM otel_traces\n--  WHERE $__conditionalAll(TraceId IN (${trace_id:singlequote}),  $trace_id) AND $__timeFilter(Timestamp)  AND ServiceName In (${serviceName:singlequote}) \n--  GROUP BY ServiceName, time \n-- ORDER BY time ASC LIMIT 100000\n\n-- -- SELECT\n-- --     toStartOfMinute(`Timestamp`) AS TimeBucket, -- 시간을 1분 단위로 버킷화\n-- --     COUNT(*) AS RequestCount -- 해당 버킷에서의 요청 개수\n-- -- FROM otel_traces\n-- -- GROUP BY TimeBucket\n-- -- ORDER BY TimeBucket\n\n\nWITH RequestCounts AS (\n  SELECT\n    toStartOfMinute(`Timestamp`) AS time,\n    ServiceName,\n    COUNT(*) AS RequestCount\n  FROM otel_traces\n  WHERE\n    ResourceAttributes['user_id'] = 'wnsrb' AND\n    $__conditionalAll(TraceId IN (${trace_id:singlequote}), $trace_id)\n    AND $__timeFilter(Timestamp)\n    AND ServiceName IN (${serviceName:singlequote})\n  GROUP BY ServiceName, time\n),\n\nTotalRequestCounts AS (\n  SELECT\n    toStartOfMinute(`Timestamp`) AS time,\n    COUNT(*) AS TotalRequestCount\n  FROM otel_traces\n  WHERE\n    ResourceAttributes['user_id'] = 'wnsrb' AND\n    $__conditionalAll(TraceId IN (${trace_id:singlequote}), $trace_id)\n    AND $__timeFilter(Timestamp)\n  GROUP BY time\n)\n\nSELECT\n  rc.time,\n  rc.ServiceName,\n  ROUND((rc.RequestCount * 100.0 / trc.TotalRequestCount), 5) AS RequestPercentage\nFROM RequestCounts rc\n\nJOIN TotalRequestCounts trc ON rc.time = trc.time\nORDER BY rc.time ASC, rc.ServiceName\nLIMIT 100000\n\n\n"
    }
   ]
  },
  {
   "title": "Response Times",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(Timestamp) as time, ServiceName,\n\tAVG(Duration) as ` ` FROM otel_traces WHERE ResourceAttributes['user_id'] = 'wnsrb' AND  $__conditionalAll(TraceId IN (${trace_id:singlequote}),  $trace_id) AND $__timeFilter(Timestamp) AND  ( Timestamp  >= $__fromTime AND Timestamp <= $__toTime ) AND ServiceName In (${serviceName:singlequote}) AND ServiceName != 'loadgenerator' GROUP BY time, ServiceName ORDER BY time ASC LIMIT 100000"
    }
   ]
  },
  {
   "title": "Error rates",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(Timestamp) as time, count(*) as ` `,\n\tServiceName FROM otel_traces WHERE ResourceAttributes['user_id'] = 'wnsrb' AND $__conditionalAll(TraceId IN (${trace_id:singlequote}),  $trace_id) AND $__timeFilter(Timestamp) AND ServiceName In (${serviceName:singlequote}) AND StatusCode= 'STATUS_CODE_ERROR' and ServiceName != 'loadgenerator' GROUP BY ServiceName, time ORDER BY time ASC LIMIT 100000"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "rawSql": "SELECT\n  toStartOfHour(TimeUnix) AS Time,\n  concat(MetricName, ' (', ResourceAttributes['service.name'], ')') AS Metric,\n  avg(Value) AS Avg_CPU_Usage\n FROM\n  otel_metrics_gauge\nWHERE\n  MetricName LIKE '%cpu%' AND\n  ResourceAttributes['user_id'] = 'wnsrb'\nGROUP BY\n  Time,\n  Metric\nORDER BY\n  Time,\n  Metric;\n",
     "selectedFormat": 4
    },
    {
     "rawSql": "WITH TotalCount AS (\nSELECT\n  toStartOfHour(TimeUnix) as avg_time,\n  AVG(Value) AS Avg_CPU_Usage,\n  concat(MetricName, ' (', ResourceAttributes['service.name'], ')') AS Metric\nFROM\n  otel_metrics_gauge\nWHERE\n  MetricName LIKE '%cpu%'\nGROUP BY\n  avg_time, Metric\nORDER BY\n  avg_time, Metric\n  )\n\n\nSELECT sum(Avg_CPU_Usage) as Total_CPU_USage, avg_time FROM TotalCount\nGroup By avg_time\n\n\n",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {
     "rawSql": "SELECT\n  toStartOfHour(TimeUnix) AS Time,\n  concat(MetricName, ' (', ResourceAttributes['service.name'], ')') AS Metric,\n  avg(Value) AS Avg_MEMORY_Usage\n FROM\n  otel_metrics_sum\nWHERE\n  ResourceAttributes['user_id'] = 'wnsrb' AND\n  MetricName LIKE '%memory%'\nGROUP BY\n  Time,\n  Metric\nORDER BY\n  Time,\n  Metric;\n",
     "selectedFormat": 4
    },
    {
     "rawSql": "WITH TotalCount AS (\nSELECT\n  toStartOfHour(TimeUnix) as avg_time,\n  AVG(Value) AS Avg_MEMORY_Usage,\n  concat(MetricName, ' (', ResourceAttributes['service.name'], ')') AS Metric\nFROM\n  otel_metrics_sum\nWHERE\n  MetricName LIKE '%memory%'\nGROUP BY\n  avg_time, Metric\nORDER BY\n  avg_time, Metric\n  )\n\n\nSELECT sum(Avg_MEMORY_Usage) as Total_MEMORY_USage, avg_time FROM TotalCount\nGroup By avg_time\n\n\n",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 67 },
   "targets": [
    {
     "rawSql": "SELECT\n  toStartOfHour(TimeUnix) AS Time,\n  concat(MetricName, ' (', ResourceAttributes['service.name'], ')') AS Metric,\n  avg(Value) AS Avg_CPU_Usage\n FROM\n  otel_metrics_sum\nWHERE\n  ResourceAttributes['user_id'] = 'wnsrb' AND\n  MetricName LIKE '%disk%'\nGROUP BY\n  Time,\n  Metric\nORDER BY\n  Time,\n  Metric;\n",
     "selectedFormat": 4
    },
    {
     "rawSql": "WITH TotalCount AS (\nSELECT\n  toStartOfHour(TimeUnix) as avg_time,\n  AVG(Value) AS Avg_CPU_Usage,\n  concat(MetricName, ' (', ResourceAttributes['service.name'], ')') AS Metric\nFROM\n  otel_metrics_sum\nWHERE\n  MetricName LIKE '%disk%'\nGROUP BY\n  avg_time, Metric\nORDER BY\n  avg_time, Metric\n  )\n\n\nSELECT sum(Avg_CPU_Usage) as Total_CPU_USage, avg_time FROM TotalCount\nGroup By avg_time\n\n\n",
     "selectedFormat": 4
    }
   ]
  },
  { "title": "Second Page", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 74 } },
  {
   "title": "Service Map",
   "type": "nodeGraph",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 75 },
   "targets": [
    {
     "rawSql": "SELECT\nServiceName as id,\nServiceName as title,\nAVG(Duration) / 1000 as mainstat, -- 예: 평균 지속 시간(ms)\nCONCAT('req cnt ', CAST(count() AS VARCHAR)) as secondarystat,\n--  AVG(Duration) / 1000 as detail__RESPONSE_TIME, -- 예: 평균 지속 시간(ms)\n--  CAST(count() AS VARCHAR) as detail__REQUEST_COUNT,\nCONCAT(CAST(sum((if(StatusCode = 'STATUS_CODE_ERROR', 1, 0)) * 100) / COUNT() AS VARCHAR) , '%') AS detail__ERROR_RATE,\n\n\nsum(if(StatusCode == 'STATUS_CODE_UNSET', 1, 0)) / COUNT() AS arc__unset_rate,\nsum(if(StatusCode == 'STATUS_CODE_OK', 1, 0)) / COUNT() AS arc__ok_rate,\nsum(if(StatusCode == 'STATUS_CODE_ERROR', 1, 0)) / COUNT() AS arc__error_rate\n-- StatusMessage as secondarystat\nFROM otel_traces\nWHERE ResourceAttributes['user_id'] = 'wnsrb'\nGROUP BY ServiceName",
     "selectedFormat": 4
    },
    {
     "rawSql": "SELECT\nconcat(s.ServiceName, '_', t.ServiceName) as id,\n s.ServiceName as source,\n t.ServiceName as target,\n AVG(t.Duration) / 1000 as detail__RESPONSE_TIME,-- 예: 평균 응답 시간 (ms)\n CAST(count() AS VARCHAR) as detail__REQUEST_COUNT, -- 예: 전체 요청 수\n CONCAT(CAST(sum((if(t.StatusCode = 'ERROR', 1, 0)) * 100) * COUNT() AS VARCHAR) , '%') AS detail__ERROR_RATE\nFROM otel_traces s\nJOIN otel_traces t ON s.SpanId = t.ParentSpanId AND s.TraceId = t.TraceId\nGROUP BY s.ServiceName, t.ServiceName",
     "selectedFormat": 4
    }
   ]
  },
  {
   "title": "Traces",
   "type": "table",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 88 },
   "targets": [
    {
     "rawSql": "SELECT min(Timestamp) as timestamp, TraceId as `Trace Id`, argMin(ServiceName, Timestamp) as `Service Name`, sum(Duration)/1000000 as Duration \nfrom otel_traces WHERE ResourceAttributes['user_id'] = 'wnsrb' AND $__conditionalAll(TraceId IN (${trace_id:singlequote}),  $trace_id)  AND ServiceName In (${serviceName:singlequote}) AND ServiceName != 'loadgenerator' AND $__timeFilter(Timestamp) GROUP BY TraceId ORDER BY Duration DESC LIMIT 100",
     "selectedFormat": 1
    }
   ]
  },
  {
   "title": "Trace Details",
   "type": "traces",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 88 },
   "targets": [
    {
     "rawSql": "SELECT TraceId as traceID, SpanId as spanID, SpanName as operationName, ParentSpanId as parentSpanID, ServiceName as serviceName, Duration/1000000 as duration, Timestamp as startTime, arrayMap(key -> map('key', key, 'value',SpanAttributes[key]), mapKeys(SpanAttributes)) as tags, arrayMap(key -> map('key', key, 'value',ResourceAttributes[key]), mapKeys(ResourceAttributes)) as serviceTags FROM otel_traces WHERE TraceId = '${trace_id}' ORDER BY startTime ASC",
     "selectedFormat": 3
    }
   ]
  },
  {
   "title": "Response Times",
   "type": "xychart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 103 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "rawSql": "SELECT $__timeInterval(Timestamp) as time, ServiceName,\n\tAVG(Duration) AS ` ` FROM otel_traces WHERE $__conditionalAll(TraceId IN (${trace_id:singlequote}),  $trace_id) AND $__timeFilter(Timestamp) AND  ( Timestamp  >= $__fromTime AND Timestamp <= $__toTime ) AND ServiceName In (${serviceName:singlequote}) AND ServiceName != 'loadgenerator' GROUP BY time, ServiceName ORDER BY time ASC LIMIT 100000"
    }
   ]
  },
  {
   "title": "Summary",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 112 },
   "targets": [
    {
     "rawSql": "WITH\n    ServiceDurations AS (\n        SELECT\n            ServiceName,\n            Duration\n        FROM\n            otel_traces\n        WHERE ResourceAttributes['user_id'] = 'wnsrb'\n    ),\n\n    ServiceStats AS (\n        SELECT\n            ServiceName,\n            AVG(Duration) AS Avg_Duration\n        FROM\n            ServiceDurations\n        GROUP BY\n            ServiceName\n    )\n\nSELECT\n    s.ServiceName as ServiceName,\n    Avg_Duration,\n    SQRT(SUM(POW(d.Duration - Avg_Duration, 2)) / COUNT(*)) AS StdDev_Duration\nFROM\n    ServiceDurations d\nJOIN\n    ServiceStats s ON d.ServiceName = s.ServiceName\nGROUP BY\n    s.ServiceName, Avg_Duration\nORDER BY\n    s.ServiceName;\n\n",
     "selectedFormat": 4
    }
   ]
  }
 ]
}