spring:
  config:
    activate:
      on-profile: dev
  session:
    jdbc:
      store-type: jdbc
      table-name: SPRING_SESSION
      initialize-schema: embedded
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ${kakao-clientid}
            client-authentication-method: client_secret_post
            redirect-uri: ${kakao-secret-redirect-uri}
            authorization-grant-type: authorization_code
            client-name: kakao
            scope:
              - profile_nickname
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

server:
  port: 8443
  ssl:
    enabled: true
    key-store: spring_key.p12
    key-store-password: 123456
    protocol: TLS
    enabled-protocols: TLSv1.2


grafana:
  account:
    loginId: ${grafana-id}
    loginPw: ${grafana-pw}
  host:
    URL: https://grafana.delitemonitor.com

